### ISSUE TITLE
documentation url?

### ISSUE THREAD

**Issue by kathlandgren** [NicOudart/PyBWE#1]
The documentation is well-written. Does it happen to be hosted at a different url, for ease of navigation? 
mkdocs.yml contains the line ""https://noudart.github.io/PyBWE" but the url appears to be defunct.

**Comment by NicOudart** [comment]
> The documentation is well-written. Does it happen to be hosted at a different url, for ease of navigation? mkdocs.yml contains the line ""https://noudart.github.io/PyBWE" but the url appears to be defunct.

@kathlandgren This was a typo, the actual URL is "https://nicoudart.github.io/PyBWE". I updated the mkdocs.yml file. Thank you for finding this mistake!

**Comment by kathlandgren** [comment]
Awesome! Perhaps it would be helpful to add this link under Documentation in README.md? I struggled to find the url, and it's nicer to interact with a website rather than click through docs/

**Comment by NicOudart** [comment]
> Awesome! Perhaps it would be helpful to add this link under Documentation in README.md? I struggled to find the url, and it's nicer to interact with a website rather than click through docs/

@kathlandgren I agree, the website will be easier to find that way. The link is now given at the beginning of the README.md.
