### ISSUE TITLE
example output formatting

### ISSUE THREAD

**Issue by kathlandgren** [NicOudart/PyBWE#2]
![image](https://github.com/NicOudart/PyBWE/assets/78450083/63a90b8c-41b8-48a0-8371-1ed7dc29d443)
![image](https://github.com/NicOudart/PyBWE/assets/78450083/c5848c1e-ff77-4477-b8d2-5fdf4def1eab)
![image](https://github.com/NicOudart/PyBWE/assets/78450083/a50cd7dd-6ef3-4249-8513-4ee547a1fd35)

Small formatting issue: both PBWE examples produce output with unsighly overlap in the text (see attached images). For all examples, the legend obscures a part of the output.

**Comment by NicOudart** [comment]
> Small formatting issue: both PBWE examples produce output with unsighly overlap in the text (see attached images). For all examples, the legend obscures a part of the output.

@kathlandgren I modified all example scripts to avoid these overlaps of labels and legends. I also updated the figures in the documentation and the JOSS article with this new display. I hope this fixes the issue.

**Comment by kathlandgren** [comment]
Yup, works great!
