### ISSUE TITLE
SSBWE - info on the singular values in the documentation

### ISSUE THREAD

**Issue by letiziagambacorta1** [NicOudart/PyBWE#5]
The SSBWE can be applied after SS representation of the signal through singular values. For the reduction of noise it is possible to select only part of this singular values according to a selected technique/method. Does the algorithm include the reduction of singular values? In case what is the method employed? I case I would add to the documentation on SSBWE.
I would consider this as an input parameter, which the user can indipendently set.

**Comment by NicOudart** [comment]
Thank you for your remark! This is indeed an important point of the SSBWE technique.

The algorithm does include the separation of singular values between the signal and noise sub-spaces. As I already mentioned in my comment on your review of the paper, the default method is currently Akaike's Information Criterion (function PySSBWE.AIC), as recommend by (Piou, 1999). It can also be set by the user manually.

As the number of selected singular values is equal to the order of the ARMA model to be determined, this is already an input parameter of PySSBWE.SSBWE, named 'order'. If set to 0 (default value), the order is determined by PySSBWE.AIC. Else, the order chosen by the user will be used.

Of course, there is no method to determine exactly the ideal order for the ARMA model, and the addition of alternative criteria to AIC could be included in a future version of the PySSBWE package.

To make this more clear for users, I updated the PySSBWE documentation with several indications that the number of selected singular values corresponds to the order of the model, ideally equal to the number target echoes in the radar signal (= number of complex sine-waves in the spectrum).

Are my modifications of the PySSBWE documentation ok for you?
