### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by letiziagambacorta1** [NicOudart/PyBWE#6]
Pandas is missing in the general requirements, but used in the examples.

**Comment by NicOudart** [comment]
Thank you for your comment. 
Pandas is not used in the examples, but only in the automated test scripts. I use it to manipulate and export the test results.
As having Pandas is not necessary to run PyBWE, but used during the tests, I decided to add a local requirement file in the "test" folder. This is the requirement file read by GitHub when running the 'test_scripts' Action.
